apiVersion: v1
kind: Service
metadata:
  name: mysql-service # Este nombre lo usa el ConfigMap (DB_HOST)
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: db-port
      port: 3306
      targetPort: 3306
      protocol: TCP
    - name: pma-port # Puerto para entrar a phpMyAdmin internamente (opcional)
      port: 8080
      targetPort: 80