apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  # [cite_start]Requisito 3.3: Variable BANNER [cite: 41, 42]
  BANNER: "Bienvenido al ITM"
  # Datos de conexi√≥n para db.php
  DB_HOST: "mysql-service"
  DB_NAME: "examen_db"
  DB_USER: "root"